<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net46</TargetFramework>
  </PropertyGroup>
  
  <PropertyGroup>
    <LangVersion>10</LangVersion>
    <AutoGenerateBindingRedirects>True</AutoGenerateBindingRedirects>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Brimstone">
      <HintPath>..\Opus Magnum\Mods\Brimstone_2.2.1\Brimstone.dll</HintPath>
    </Reference>
    <Reference Include="Lightning">
      <HintPath>..\Opus Magnum\ModdedLightning.exe</HintPath>
    </Reference>
    <Reference Include="MMHOOK_ModdedLightning">
      <HintPath>..\Opus Magnum\MMHOOK_ModdedLightning.dll</HintPath>
    </Reference>
    <Reference Include="Lightning">
      <HintPath>..\Opus Magnum\ModdedLightning.exe</HintPath>
    </Reference>
    <Reference Include="Mono.Cecil">
      <HintPath>..\Opus Magnum\Mono.Cecil.dll</HintPath>
    </Reference>
    <Reference Include="MonoMod">
      <HintPath>..\Opus Magnum\MonoMod.exe</HintPath>
    </Reference>
    <Reference Include="MonoMod.RuntimeDetour">
      <HintPath>..\Opus Magnum\MonoMod.RuntimeDetour.dll</HintPath>
    </Reference>
    <Reference Include="MonoMod.RuntimeDetour.HookGen">
      <HintPath>..\Opus Magnum\MonoMod.RuntimeDetour.HookGen.exe</HintPath>
    </Reference>
    <Reference Include="MonoMod.Utils">
      <HintPath>..\Opus Magnum\MonoMod.Utils.dll</HintPath>
    </Reference>
	<Reference Include="ReductiveMetallurgy">
	  <HintPath>..\Opus Magnum\Mods\ReductiveMetallurgy_1.0.1\ReductiveMetallurgy.dll</HintPath>
	</Reference>
	<Reference Include="TrueAnimismus">
	  <HintPath>..\Opus Magnum\Mods\TrueAn_1.0.6\TrueAn.dll</HintPath>
	</Reference>
    <Reference Include="YamlDotNet">
      <HintPath>..\Opus Magnum\YamlDotNet.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Reference Update="System">
      <CopyLocal>False</CopyLocal>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Reference Update="System.Core">
      <CopyLocal>False</CopyLocal>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Reference Update="System.Data">
      <CopyLocal>False</CopyLocal>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Reference Update="System.Drawing">
      <CopyLocal>False</CopyLocal>
    </Reference>
  </ItemGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="copy /Y &quot;..\UncommonAlchemicalPrimes\bin\Debug\net46\UncommonPrimes.dll&quot; &quot;..\Opus Magnum\Mods\UncommonAlchemicalPrimes\UncommonPrimes.dll&quot; &amp;&amp; cd /d &quot;..\Opus Magnum&quot; &amp;&amp; ModdedLightning.exe" />
  </Target>

</Project>
